config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'products/show'
  devise_for :customers
  # get 'categories/index'
  # get 'categories/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Customer
  resources :customers
  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  # Category
  get 'category/:id', to: 'carts#show', as: 'category'

  # Static pages
  root to: 'pages#index'

  # Others
  match '/pages/add_to_cart' => 'pages#add_to_cart', :as => :add_to_cart, via: [:post]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true
class Author < ApplicationRecord
    has_one_attached :image
    has_many :products
    validates :first_name, :last_name, presence: true
    
    # Get formatted version of author's name
    def name
      "#{last_name}, #{first_name} #{middle_name}"
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories, :dependent => :destroy
    has_many :products, through: :product_categories
    validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status
  has_many :order_items

  before_validation :set_order_status, on: :create
  before_save :update_subtotal

  def subtotal
      order_items.collect { |oi | oi.valid? ? (oi.quantity * oi.price) : 0}.sum
  end

  private
    def set_order_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present

  before_save :finalize

  def price
    if persisted? 
      self[:price]
    else
      product.price
    end
  end

  def total_price
    price * quantity
  end

  private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not active.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not valid order.")
      end
    end

    def finalize
      self[:price] = price
      self[:total_price] = quantity * self[:price]
    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :author, optional: true
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :order_items
  mount_uploader :image, ImageUploader

  validates :title, :price, :qoh_new, presence: true
  validates :qoh_new, numericality: {only_integer: true}
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :sale_discount, numericality: {greater_than_or_equal_to: 0.01, less_than_or_equal_to: 1}, allow_blank: true
  validates :length, :width, :height, :weight, numericality: {greater_than_or_equal_to: 0}, allow_blank: true
  validates :qoh_used, numericality: {only_integer: true, greater_than_or_equal_to: 0}, allow_blank: true

  def short_description;
    truncate(:description, length: 15)
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
    validates :name, :postal_abbreviation, presence: true
    validates :gst, :hst, :pst, numericality: true, allow_blank: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @categories = Category.all
        @products_on_sale = Product.where('sale_discount NOT NULL')
    end

    def cart 
    end

    def add_to_cart
        raise "#{params[:order_item][:quantity]}"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laplace Gifts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to "Laplace Gifts", root_path, class: "nav-link navbar-brand"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link"%>
            </li>

            <% if customer_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#">
                    <%= current_customer.email %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'My cart', cart_path %></li>
                    <li><%= link_to 'Profile', edit_customer_registration_path %></li>
                    <li><%= link_to 'Log out', destroy_customer_session_path, method: :delete %></li>
                  </ul>
                </li>
            <% else %>
              <li><%= link_to 'Log In', new_customer_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Laplace Gifts 2018</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
    <div class="row">
        <div class= "col-lg-3">
            <h1 class="my-4">Shop by Category:</h1>
            <div class="list-group">
                <% @categories.each do |category| %>
                    <%= link_to category.name, category, class:'list-group-item' %>
                <% end %>
            </div>
        </div>

        <div class= "col-lg-9">
            <%= render :partial => 'partials/carousel'%>
            <div class="row">
                <%= render :partial => 'partials/product_card', :collection => @products_on_sale, :as => :product%>
            </div>
        </div>
    </div>
</div>

app/views/partials/_carousel.html.erb
<div id="featured_products_carousel" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#featured_products_carousel" data-slide-to="0" class="active"></li>
        <li data-target="#featured_products_carousel" data-slide-to="1" class="active"></li>
        <li data-target="#featured_products_carousel" data-slide-to="2" class="active"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
            <%= image_tag('http://placehold.it/900x350', class:"d-block img-fluid") %>
        </div>
        <div class="carousel-item">
            <%= image_tag('http://placehold.it/900x350', class:"d-block img-fluid") %>        
        </div>
        <div class="carousel-item">
            <%= image_tag('http://placehold.it/900x350', class:"d-block img-fluid") %>        
        </div>
    </div>
    <a class="carousel-control-prev" href="#featured_products_carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#featured_products_carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

app/views/partials/_cart_row.html.erb
<div class='well'>
    <div class='row'>
        <div class='col-xs-8'>
            <h4><%= product.title %></h4>
        </div>

        <div class='col-xs-4'>
            <%= form_for order_item, remote: true do |f| %>
                <h4 class='text-right'>Unit Price: <span style='color:green'><%= number_to_currency order_item.price%></span></h4>
                <div class='row'>
                    <div class="col-xs-4">
                        <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
                        <%= f.hidden_field :product_id, value: product.id %>
                    </div>
                    <div class="col-xs-8 text-right">
                        <div class="btn-group">
                            <%= f.submit "Update Quantity", class: "btn btn-primary" %>
                            <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.title}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
                        </div>
                    </div>
                </div>
                <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
            <% end %>
        </div>
    </div>
</div>

app/views/partials/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/partials/_product_card.html.erb
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <% if product.image.url.nil?%>
            <%= image_tag('NoImageAvailablePicture.png', alt: 'Placeholder image', class:'img_fluid') %>
        <% else %>
            <%= image_tag(product.image.url(:detail_size), class:'img-fluid')%>
        <% end %>

        <div class="card-body">
            <h5 class="card-title">
            <%= link_to product.title, product %>
            </h5>
            <h6>
                <% if product.sale_discount.nil? %>
                    <%= number_to_currency(product.price)%>
                <% else %>
                    <h6><s><%= number_to_currency(product.price) %></s> <%= number_to_currency(product.price - product.price * product.sale_discount)%> (-<%= number_to_percentage(product.sale_discount * 100, precision: 2)%>)</h6>
                <% end %>
            </h6>
            <p class="card-text"><%= "#{product.description[0,75]}..." %></p>
        </div>
        <div class="card-footer">
            <<small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>>
        </div>
    </div>
</div>

app/views/partials/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.title %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :price, value: product.price%>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/partials/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
    <div class ='alert alert-danger'>
        <ul>
            <% @order_item.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
    </div>
<% end %>

<% if @order_items.size == 0 %>
    <p class='text-center'>
        There are no items in your shopping cart. Please <%= link_to "go back", root_path %> and add some items to your cart.
    </p>
<% else %>
    <% @order_items.each do |order_item| %>
        <%= render 'partials/cart_row', product: order_item.product, order_item: order_item, show_total: true%>
    <% end %>
<% end %>